### PR TITLE
テスト追加

### LINKED ISSUE #46: instagram 複数の動画

### LINKED ISSUE #49: テスト追加(pytest)

### PR DESCRIPTION
**Pull request by lazmond3**
Close #49
Close #46

### CODE REVIEW

**Comment by lazmond3** [comment]
Close #46

**Comment by lazmond3** [comment]
.buildep

**Comment by lazmond3** [comment]
### TODO

- いま 5枚目だけなので、6枚目についてもやってみる。
- twitter についてもやってみる
- dump戦略修正必要？

**Comment by lazmond3** [comment]
.buildep

**Comment by Itanvee** [comment]
It's a Fintech company
 
 Register with the link and visit "Neufund"  https://neufund.co/r/?a=jamesbethel66@gmail.com

It's actually a cryptocurrency investment company , they also operate on real estate, oil asset and mortgages as a back up financial aid.

**Comment by Itanvee** [comment]
> #### terraform plan every: 1581fb3
> #### Terraform Format and Style 🖌`success`
> #### Terraform Initialization ⚙️`success`
> #### Terraform Plan 📖`success`
> 
> <details><summary>Show Plan</summary>
> 
> ```terraform
> module.ecr.aws_ecr_repository.main: Refreshing state... [id=discord-instagram-bot]
> module.iam.aws_dynamodb_table.tweet_json: Refreshing state... [id=tweet_json]
> module.cloudwatch.aws_cloudwatch_log_group.main: Refreshing state... [id=/aws/ecs/discord-instagram-bot]
> module.ssm.aws_ssm_parameter.consumer_key: Refreshing state... [id=consumer_key]
> module.ssm.aws_ssm_parameter.mid: Refreshing state... [id=mid]
> module.iam.aws_dynamodb_table.instagram_json: Refreshing state... [id=instagram_json]
> aws_s3_bucket.discord-python-video: Refreshing state... [id=discord-python-video]
> module.ssm.aws_ssm_parameter.consumer_secret: Refreshing state... [id=consumer_secret]
> module.ssm.aws_ssm_parameter.v_aws_access_key_id: Refreshing state... [id=v_aws_access_key_id]
> module.ssm.aws_ssm_parameter.token: Refreshing state... [id=token]
> module.ecs.aws_ecs_cluster.main: Refreshing state... [id=arn:aws:ecs:ap-northeast-1:554506578892:cluster/discord-instagram-bot]
> aws_s3_bucket.discord-python-image: Refreshing state... [id=discord-python-image]
> module.iam.aws_dynamodb_table.dynamo_kvs: Refreshing state... [id=dynamo_kvs]
> module.vpc.aws_vpc.main: Refreshing state... [id=vpc-0219c5015d0627f06]
> module.ssm.aws_ssm_parameter.sessionid: Refreshing state... [id=sessionid]
> module.ssm.aws_ssm_parameter.v_aws_secret_access_key: Refreshing state... [id=v_aws_secret_access_key]
> module.iam.aws_iam_role.ecs_task_execution_role: Refreshing state... [id=EcsTaskRole-discord-instagram-bot]
> module.iam.aws_iam_policy.iam_dynamo_instagram_json: Refreshing state... [id=arn:aws:iam::554506578892:policy/instagram_json-policy]
> module.iam.aws_iam_policy.iam_dynamo_tweet_json: Refreshing state... [id=arn:aws:iam::554506578892:policy/tweet_json-policy]
> module.iam.aws_iam_role_policy_attachment.tweet_json: Refreshing state... [id=EcsTaskRole-discord-instagram-bot-20211114092543431800000001]
> module.iam.aws_iam_role_policy_attachment.instagram_json: Refreshing state... [id=EcsTaskRole-discord-instagram-bot-20211114210746716300000001]
> module.ecs.aws_ecs_task_definition.main: Refreshing state... [id=discord-instagram-bot-task-definition]
> module.iam.aws_iam_role_policy.cloudwatch_logs: Refreshing state... [id=EcsTaskRole-discord-instagram-bot:cloudwatch_logs]
> module.iam.aws_iam_role_policy.ecs_to_ssm: Refreshing state... [id=EcsTaskRole-discord-instagram-bot:ecs_to_ssm]
> module.iam.aws_iam_role_policy_attachment.ecs_task_execution_role_policy_for_ecr: Refreshing state... [id=EcsTaskRole-discord-instagram-bot-20210515144659286700000001]
> aws_s3_bucket_policy.discord-python-video-policy: Refreshing state... [id=discord-python-video]
> module.vpc.aws_subnet.privates[1]: Refreshing state... [id=subnet-007456b5f4d45d89f]
> module.security.aws_security_group.alb: Refreshing state... [id=sg-0da582b80a2919b39]
> module.vpc.aws_subnet.privates[2]: Refreshing state... [id=subnet-0aed969abfb5a6b8a]
> module.security.aws_security_group.ecs: Refreshing state... [id=sg-086c267e1e2207c43]
> module.vpc.aws_subnet.publics[2]: Refreshing state... [id=subnet-0811d6780fa40db10]
> module.vpc.aws_subnet.privates[0]: Refreshing state... [id=subnet-0fb948f228d9d112f]
> module.vpc.aws_subnet.publics[0]: Refreshing state... [id=subnet-0b3f607aa8028d7d7]
> module.vpc.aws_subnet.publics[1]: Refreshing state... [id=subnet-011f1a6e62c871778]
> module.vpc.aws_internet_gateway.main: Refreshing state... [id=igw-07adf71781ae87ed1]
> module.vpc.aws_route_table.privates[1]: Refreshing state... [id=rtb-0b972285c43ef8586]
> module.vpc.aws_route_table.privates[2]: Refreshing state... [id=rtb-0292c7a41f76eb5cf]
> module.vpc.aws_route_table.privates[0]: Refreshing state... [id=rtb-09dfe003f37f6fa01]
> module.vpc.aws_route_table.public: Refreshing state... [id=rtb-0e45a090904c9ab1d]
> module.ecs.aws_ecs_service.main: Refreshing state... [id=arn:aws:ecs:ap-northeast-1:554506578892:service/discord-instagram-bot/discord-instagram-bot]
> module.vpc.aws_route_table_association.privates[0]: Refreshing state... [id=rtbassoc-06e92ec6691013325]
> module.vpc.aws_route_table_association.privates[1]: Refreshing state... [id=rtbassoc-0730f79efc3000e03]
> module.vpc.aws_route_table_association.privates[2]: Refreshing state... [id=rtbassoc-0bab84d600257f8aa]
> module.vpc.aws_route_table_association.public[0]: Refreshing state... [id=rtbassoc-0a11d6b569f35e936]
> module.vpc.aws_route_table_association.public[2]: Refreshing state... [id=rtbassoc-086f9e70679e407a4]
> module.vpc.aws_route_table_association.public[1]: Refreshing state... [id=rtbassoc-0b0ccfb579951dc58]
> module.vpc.aws_route.public: Refreshing state... [id=r-rtb-0e45a090904c9ab1d1080289494]
> aws_s3_bucket_policy.discord-python-image-policy: Refreshing state... [id=discord-python-image]
> module.iam.aws_iam_policy.iam_dynamo_dynamo_kvs: Refreshing state... [id=arn:aws:iam::554506578892:policy/dynamo_kvs-policy]
> module.iam.aws_iam_role_policy_attachment.dynamo_kvs: Refreshing state... [id=EcsTaskRole-discord-instagram-bot-20211124164410554700000001]
> 
> Note: Objects have changed outside of Terraform
> 
> Terraform detected the following changes made outside of Terraform since the
> last "terraform apply":
> 
>   # module.ecs.aws_ecs_task_definition.main has been changed
>   ~ resource "aws_ecs_task_definition" "main" {
>         id                       = "discord-instagram-bot-task-definition"
>       + tags                     = {}
>         # (10 unchanged attributes hidden)
>     }
> 
> Unless you have made equivalent changes to your configuration, or ignored the
> relevant attributes using ignore_changes, the following plan may i.               It's a Fintech company
 
 Register with the link and visit "Neufund"  https://neufund.co/r/?a=jamesbethel66@gmail.com

It's actually a cryptocurrency investment company , they also operate on real estate, oil asset and mortgages as a back up financial aid💹🗝️🛡️

**Pull request merged**
